version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "montly"

  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "montly"