# Parameters

[template]
cargo_generate_version = ">=0.22.0"
exclude = ["assets"]

[placeholders.package_name]
type = "string"
prompt = "What is the name of the package?"

[placeholders.license]
type = "string"
prompt = "What licenses will the project have?"
default = "all"
choices = ["all", "MIT", "APACHE"]

[placeholders.email]
type = "string"
prompt = "What is your email? (CONTRIBUTING, LICENSE, etc)"

[placeholders.toolchain.channel]
type = "string"
prompt = "What is the rust toolchain version?"
choices = ["stable", "beta", "nightly"]

# Conditions
## License

[conditional.'license != "MIT" && license != "all"']
ignore = ["LICENSE-MIT"]

[conditional.'license != "APACHE" && license != "all"']
ignore = ["LICENSE-APACHE"]