# Parameters

[template]
cargo_generate_version = ">=0.22.0"
ignore = ["*.png, Cargo.toml"]

[placeholders.package_name]
type = "string"
prompt = "What is the name of the package?"

[placeholders.package_description]
type = "string"
prompt = "Enter a project description"

[placeholders.license]
type = "string"
prompt = "What licenses will the project have?"
default = "all"
choices = ["all", "MIT", "APACHE"]

[placeholders.email]
type = "string"
prompt = "What is your email? (CONTRIBUTING, LICENSE, etc)"

[placeholders.codeowner]
type = "string"
prompt = "What is your github username? (CODEOWNERS)"

[placeholders.toolchain]
type = "string"
prompt = "What is the rust toolchain version?"
choices = ["stable", "beta", "nightly"]

[placeholders.github_release]
type = "bool"
prompt = "Do you want to create a github release?"
default = false

## Dependencies
[placeholders.sentry]
type = "bool"
prompt = "Do you want to use sentry?"
default = false

# Conditions
## License

[conditional.'license == MIT']
ignore = ["LICENSE-APACHE"]

[conditional. 'license == APACHE']
ignore = ["LICENSE-MIT"]

## Workflows
[conditional.'github_release == false']
ignore = [".github/workflows/release.yaml"]

## Dependencies
[conditional. 'sentry == true']
type = "string"
name = "sentry_dsn"
prompt = "What is your sentry dsn?"
default = "https://examplePublicKey@o0.ingest.sentry.io/0"

## Files
[conditional. 'sentry == false']
ignore = ["./src/functions.rs", ".env.example"]
